// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNwyEJauZgYIck0OKdk5rT01aJHS_ASUw',
    appId: '1:839130880338:android:7fac89ffb776c4cd45828b',
    messagingSenderId: '839130880338',
    projectId: 'harmoniq-prod',
    storageBucket: 'harmoniq-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdr76jt4GNlkz-2J5qcUI1G9OfUP-U18w',
    appId: '1:839130880338:ios:70c861f89ae7c76345828b',
    messagingSenderId: '839130880338',
    projectId: 'harmoniq-prod',
    storageBucket: 'harmoniq-prod.firebasestorage.app',
    iosBundleId: 'net.metalbrain.harmoniq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdr76jt4GNlkz-2J5qcUI1G9OfUP-U18w',
    appId: '1:839130880338:ios:70c861f89ae7c76345828b',
    messagingSenderId: '839130880338',
    projectId: 'harmoniq-prod',
    storageBucket: 'harmoniq-prod.firebasestorage.app',
    iosBundleId: 'net.metalbrain.harmoniq',
  );
}
